[package]
name = "plutonic"
version = "0.1.0"
edition = "2021"

[dependencies]
apca = "0.30.0"
dotenv = "0.15.0"
futures = "0.3.31"
tokio = { version = "1.44.2", features = ["full"] }
tokio-util = "0.7.15"
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
